[package]
name = "bin-without-main-with-lib"
version = "0.1.0"
authors = ["Takuya SHIOZAKI <tshiozak@bsdclub.org>"]

[dependencies]

[[bin]]
name = "bin1"

[[bin]]
name = "bin2"
path = "src/bin/bin2.rs"

[lib]
name = "hoge"
